# Generated by Django 5.2.4 on 2025-07-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_bookcondition_alter_author_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Trade description", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional trade details or notes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("counter_offered", "Counter Offered"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "initiator_pays_shipping",
                    models.BooleanField(
                        default=True, help_text="Does initiator pay their own shipping?"
                    ),
                ),
                (
                    "responder_pays_shipping",
                    models.BooleanField(
                        default=True, help_text="Does responder pay their own shipping?"
                    ),
                ),
                (
                    "cash_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cash amount (+ means initiator pays responder, - means responder pays initiator)",
                        max_digits=8,
                    ),
                ),
                ("proposed_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this trade offer expires", null=True
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="User who started the trade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        help_text="User responding to the trade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_responded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-proposed_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False, help_text="True for automated system messages"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="trades.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TradeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of this offer"),
                ),
                (
                    "cash_difference",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "offered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="trades.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated value of this book",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("image1", models.ImageField(blank=True, upload_to="trade_images/")),
                ("image2", models.ImageField(blank=True, upload_to="trade_images/")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Who owns this book",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trades.trade",
                    ),
                ),
            ],
            options={
                "unique_together": {("trade", "book", "owner")},
            },
        ),
    ]
