version: '3'
services:
  booktrader:
    build: 
      context: ./booktrader
    ports:
      - 8000:8000
    volumes:
      - static:/static
    entrypoint: /usr/local/bin/python3.11
    command: manage.py runserver 0.0.0.0:8000
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - booktrader
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  # tests:
  #   build: .
  #   volumes:
  #     - .:/booktrader/
  #   entrypoint: /usr/local/bin/python3.11
  #   command: manage.py test
volumes:
  postgres_data:  
  static:

