version: "3.11"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/voltronflamingo/
    entrypoint: /usr/local/bin/python3.11
    command: manage.py runserver 0.0.0.0:8000
  # tests:
  #   build: .
  #   volumes:
  #     - .:/voltronflamingo/
  #   entrypoint: /usr/local/bin/python3.11
  #   command: manage.py test
