version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/voltronflamingo/
    entrypoint: /usr/local/bin/python3.7
    command: manage.py runserver 0.0.0.0:8000
  tests:
    build: .
    volumes:
      - .:/voltronflamingo/
    entrypoint: /usr/local/bin/python3.7
    command: manage.py test
