version: '3'

services:
  booktrader:
    ports: 
     - 8000:8000
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PASSWORD: dbpassword
    build: 
      context: ./booktrader
      dockerfile: ./Dockerfile
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/workspace
    links: 
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dbpassword

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - booktrader
      - db
    ports:
      - 80:80
    volumes:
      - .:/workspace