version: '3'

services:
  workspace:
    ports: 
     - 8000:8000
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PASSWORD: dbpassword
    build: 
      context: ..
      dockerfile: book-trader/.devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    links: 
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dbpassword