# Generated by Django 5.2.4 on 2025-07-17 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True)),
                ("acquired_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_available_for_trade", models.BooleanField(default=False)),
                ("is_available_for_auction", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="death_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non_fiction", "Non-Fiction"),
                    ("mystery", "Mystery"),
                    ("romance", "Romance"),
                    ("sci_fi", "Science Fiction"),
                    ("fantasy", "Fantasy"),
                    ("biography", "Biography"),
                    ("history", "History"),
                    ("self_help", "Self Help"),
                    ("business", "Business"),
                    ("textbook", "Textbook"),
                    ("children", "Children"),
                    ("young_adult", "Young Adult"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Language code (e.g., en, es, fr)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original retail price",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="founded_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rating",
            name="review",
            field=models.TextField(blank=True, help_text="Optional written review"),
        ),
        migrations.AddField(
            model_name="rating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="ISBN-10 or ISBN-13", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "book")},
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
        ),
        migrations.AddField(
            model_name="bookcondition",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="bookcondition",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookcondition",
            unique_together={("book", "owner")},
        ),
    ]
