# Generated by Django 5.2.4 on 2025-07-17 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, default="US", max_length=100)),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Tell others about your reading interests"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "preferred_genres",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of favorite genres"
                    ),
                ),
                ("willing_to_ship_internationally", models.BooleanField(default=False)),
                (
                    "max_shipping_distance_miles",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum distance willing to ship (leave blank for no limit)",
                        null=True,
                    ),
                ),
                (
                    "reputation_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="User reputation based on trading/auction history",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Email/phone verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reputation_type",
                    models.CharField(
                        choices=[
                            ("auction_complete", "Completed Auction"),
                            ("trade_complete", "Completed Trade"),
                            ("positive_feedback", "Positive Feedback"),
                            ("negative_feedback", "Negative Feedback"),
                            ("verified_email", "Email Verified"),
                            ("verified_phone", "Phone Verified"),
                            ("account_penalty", "Account Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(-5.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_auction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auctions.auction",
                    ),
                ),
                (
                    "related_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trades.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
